codecov:
  require_ci_to_pass: yes

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - main
transcode-server:
  build:
    context: tanscodingservice
    dockerfile: Dockerfile
  ports:
    - "8083:8083"
  environment:
    - RTMP_SERVER=rtmp://rtmp-server:1935
  volumes:
    - stream-volume:/home/streams
  content-server:
    build:
      context: contentservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - stream-volume:/home/streams