name: Commeow Code Coverage

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'
    
jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        gradle-version: 7.5.1
      
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew test
      shell: bash

    - name: Find test report files
      run: |
        echo "TEST_REPORT_FILES=$(find . -type f -name 'jacocoTestReport.xml' | sed 's/ /", "/g' | tr '\n' ',')" >> $GITHUB_ENV
      shell: bash

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ${{ env.TEST_REPORT_FILES }}
